version: '3.5'

services:
  zabbix-agent:
    image: 'zabbix/zabbix-agent:ubuntu-latest'
    restart: 'always'

  zabbix-server:
    image: 'zabbix/zabbix-server-mysql:ubuntu-latest'
    ports:
      - '10051:10051'
    links:
      - 'zabbix-agent'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/etc/timezone:/etc/timezone:ro'
    environment:
      - 'ZBX_ENABLE_SNMP_TRAPS=true'
    env_file: './mysql-vars.env'
    restart: 'always'

  zabbix-web-nginx-mysql:
    #image: 'zabbix/zabbix-web-nginx-mysql:ubuntu-latest'
    build:
      context: './dockerfiles'
      dockerfile: 'ZBXFront'
    ports:
      - '80:8080'
    links:
      - 'zabbix-server'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/etc/timezone:/etc/timezone:ro'
    environment:
      - 'ZBX_SERVER_HOST=zabbix-server'
      - 'PHP_TZ=Asia/Tokyo'
    env_file: './mysql-vars.env'
    restart: 'always'
