version: '3.5'

services:
    zabbix-agent:
        image: 'zabbix/zabbix-agent'
        restart: 'always'

    zabbix-server:
        #image: 'zabbix/zabbix-server-mysql:latest'
        build:
            context: './dockerfiles'
            dockerfile: 'ZBXServer'
        ports:
            - '10051:10051'
        links:
            - 'zabbix-agent'
        volumes:
            - '/etc/localtime:/etc/localtime:ro'
            - '/etc/timezone:/etc/timezone:ro'
            - './alertscripts:/usr/lib/zabbix/alertscripts:ro'
        environment:
            - 'ZBX_ENABLE_SNMP_TRAPS=true'
        env_file: './mysql-vars.env'
        restart: 'always'

    zabbix-web-nginx-mysql:
        #image: 'zabbix/zabbix-web-nginx-mysql:latest'
        build:
            context: './dockerfiles'
            dockerfile: 'ZBXFront'
        ports:
            - '80:8080'
        links:
            - 'zabbix-server'
        volumes:
            - '/etc/localtime:/etc/localtime:ro'
            - '/etc/timezone:/etc/timezone:ro'
        environment:
            - 'PHP_TZ=Asia/Tokyo'
        env_file: './mysql-vars.env'
        restart: 'always'

